name: Branch Automation

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: "Select Action"
        type: choice
        options:
          - staging
          - uat
        required: true

      repos:
        description: "Comma separated repository names (example: web,reports,traceui2)"
        required: true

      pipelines:
        description: "Comma separated CodePipeline names (Required for UAT)"
        required: false

jobs:
  branch-automation:
    runs-on: ubuntu-latest

    env:
      ACTION_TYPE: ${{ inputs.action_type }}
      REPOS: ${{ inputs.repos }}
      PIPELINES: ${{ inputs.pipelines }}
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests boto3

      - name: Run Branch Automation Script
        run: python branch_automation.py
