name: Branch Automation

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: "Select Action"
        type: choice
        options:
          - staging
          - uat
        required: true

      repos:
        description: "Comma separated repository names (example: web,reports,traceui2)"
        required: true

      pipelines:
        description: "Comma separated CodePipeline names (Required for UAT)"
        required: true

jobs:
  branch-automation:
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # ← Required for OIDC
      contents: read       # ← Required to checkout code

    env:
      ACTION_TYPE: ${{ inputs.action_type }}
      REPOS: ${{ inputs.repos }}
      PIPELINES: ${{ inputs.pipelines }}
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::384570460482:role/Code-Pipeline-Github-WebIdentity
          aws-region: us-east-1

      - name: Run Branch Automation Script
        run: python testing-branch.py
